name: Latest videos in the channel
on:
  schedule:
    # Runs every 5min
    - cron: '*/5 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC96jD91_XC7k5julp1y7x7A"
